name: Fetch Minecraft Lang

on:
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: '0 6 * * *'  # Daily at 6 AM UTC

jobs:
  fetch-lang:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install jq & curl
        run: sudo apt-get update && sudo apt-get install -y jq curl

      - name: Fetch latest Minecraft version
        id: get_version
        run: |
          VERSION_JSON=$(curl -s https://piston-meta.mojang.com/mc/game/version_manifest_v2.json)
          LATEST_VERSION=$(echo "$VERSION_JSON" | jq -r '.latest.release')
          VERSION_URL=$(echo "$VERSION_JSON" | jq -r --arg VER "$LATEST_VERSION" '.versions[] | select(.id == $VER) | .url')

          echo "Latest version: $LATEST_VERSION"
          echo "version=$LATEST_VERSION" >> $GITHUB_OUTPUT
          echo "version_url=$VERSION_URL" >> $GITHUB_OUTPUT

      - name: Get assets hash for latest version
        id: get_assets
        run: |
          VERSION_URL=${{ steps.get_version.outputs.version_url }}
          VERSION_DATA=$(curl -s "$VERSION_URL")
          ASSETS_INDEX=$(echo "$VERSION_DATA" | jq -r '.assetIndex.url')

          echo "assets_url=$ASSETS_INDEX" >> $GITHUB_OUTPUT

      - name: Download all language files
        run: |
          ASSETS_URL=${{ steps.get_assets.outputs.assets_url }}
          ASSET_DATA=$(curl -s "$ASSETS_URL")

          mkdir -p lang
          echo "$ASSET_DATA" | jq -r '.objects | to_entries[] | select(.key | startswith("minecraft/lang/") and endswith(".json")) | "\(.key) \(.value.hash)"' | while read -r KEY HASH; do
            FILE_NAME=$(basename "$KEY")
            LANG_URL="https://resources.download.minecraft.net/${HASH:0:2}/$HASH"
            echo "Downloading $FILE_NAME..."
            curl -s -o "lang/$FILE_NAME" "$LANG_URL"
          done
          
      - name: Commit lang files
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git pull --rebase origin main

          git add lang/
          git commit -m "Update all Minecraft lang files (latest)" || echo "No changes"
          git push origin HEAD:main

  fetch-snapshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: snapshot

      - name: Setup tools
        run: sudo apt-get update && sudo apt-get install -y jq curl

      - name: Fetch latest snapshot version
        id: snapshot_version
        run: |
          JSON=$(curl -s https://piston-meta.mojang.com/mc/game/version_manifest_v2.json)
          LATEST_SNAPSHOT=$(echo "$JSON" | jq -r '.latest.snapshot')
          VERSION_URL=$(echo "$JSON" | jq -r --arg VER "$LATEST_SNAPSHOT" '.versions[] | select(.id == $VER) | .url')
          echo "version=$LATEST_SNAPSHOT" >> $GITHUB_OUTPUT
          echo "version_url=$VERSION_URL" >> $GITHUB_OUTPUT

      - name: Get snapshot asset index url
        id: snapshot_assets
        run: |
          DATA=$(curl -s "${{ steps.snapshot_version.outputs.version_url }}")
          ASSETS_URL=$(echo "$DATA" | jq -r '.assetIndex.url')
          echo "assets_url=$ASSETS_URL" >> $GITHUB_OUTPUT

      - name: Download all snapshot language files
        run: |
          ASSETS_URL=${{ steps.get_assets.outputs.assets_url }}
          ASSET_DATA=$(curl -s "$ASSETS_URL")

          mkdir -p lang
          echo "$ASSET_DATA" | jq -r '.objects | to_entries[] | select(.key | startswith("minecraft/lang/") and endswith(".json")) | "\(.key) \(.value.hash)"' | while read -r KEY HASH; do
            FILE_NAME=$(basename "$KEY")
            LANG_URL="https://resources.download.minecraft.net/${HASH:0:2}/$HASH"
            echo "Downloading $FILE_NAME..."
            curl -s -o "lang/$FILE_NAME" "$LANG_URL"
          done


      - name: Commit lang files
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git pull --rebase origin snapshot

          git add lang/
          git commit -m "Update all Minecraft lang files (latest)" || echo "No changes"
          git push origin HEAD:snapshot



